server:
    port: 8099
spring:
    application:
        name: admin
    profiles:
      active: dev

#develop
---
spring:
    profiles: dev
    thymeleaf:
        cache: false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: 'jdbc:mysql://172.18.10.79:3306/dt-balance?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false'
        username: root
        password: GIChain@2018
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: 'SELECT 1 FROM DUAL'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500'
    jpa:
        database: MYSQL
        show-sql: false
        hibernate.ddl-auto: none
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    resources:
        static-locations: classpath:/static/
    redis:
        host: 172.18.10.79
        port: 6379
        password: GIChain@2018
        jedis:
            pool:
                active: 8
                max-wait: 1ms
                max-idle: 8
                min-idle: 0
        timeout: 30000ms

multipart:
    maxFileSize: 50Mb
    maxRequestSize: 50Mb
    enabled: true

jg:
    masterSecret: 0a3f84272c5ed6a80fa3e598
    appKey: e3fee986bb06ca736167692e
    audience: test

sys:
    certUrl: '/Users/liqi/Downloads/RootCert.crt'
    midUrl: 'http://localhost:8090/'

#seafile http replace url
    seaHttpOnlineUrl: localhost
    seaHttpInnerUrl: localhost

#seafile service url
    seafileUrl: 'https://localhost'
#seafile username
    seafileUserName: 'admin@seafile.local'
#seafile password
    seafilePassword: eeCh9aiH
#seafile zi liao ku id
    seafileRepoId: '6e097a87-4200-4cbc-b591-051a27d83d23'

    telegramChatId: -205165964
    telegramURL: "http://sendmessage.tbots.pro/"

    fastdfsIP: "172.18.10.79"
    fastdfsPort: 22122
    fastdfsG_tracker_http_port: 7738
    fastdfsG_network_timeout: 180
    fastdfsG_connect_timeout: 60
    fastdfsNginx: "http://172.18.10.79/"
    fastdfsSize: 1024

#test
---
spring:
    profiles: test
    thymeleaf:
        cache: false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: 'jdbc:mysql://172.18.10.89:3306/dt-balance?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false'
        username: root
        password: Hefeidalian123!@#
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: 'SELECT 1 FROM DUAL'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500'
    jpa:
        database: MYSQL
        show-sql: false
        hibernate.ddl-auto: none
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    resources:
        static-locations: classpath:/static/
    redis:
        host: 148.66.11.201
        port: 6528
        password: 123456
        jedis:
            pool:
                active: 8
                max-wait: 1ms
                max-idle: 8
                min-idle: 0
        timeout: 30000ms

multipart:
    maxFileSize: 50Mb
    maxRequestSize: 50Mb
    enabled: true

jg:
    masterSecret: 0a3f84272c5ed6a80fa3e598
    appKey: e3fee986bb06ca736167692e
    audience: test



